[build]
  # ビルドコマンド
  command = "npm run build"
  
  # ビルド出力ディレクトリ
  publish = "build"
  
  # Node.js のバージョン
  environment = { NODE_VERSION = "18" }

# リダイレクト設定（React Router対応）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ヘッダー設定
[[headers]]
  for = "/*"
  [headers.values]
    # セキュリティヘッダー
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # HTTPS強制
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# 静的アセットのキャッシュ設定
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 開発環境用の設定
[context.development]
  command = "npm start"

# 本番環境用の設定
[context.production]
  command = "npm run build"
